version: '3.7'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=instrument_storage'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '8002:5432'
    volumes:
      - db-data:/var/lib/postgresql/instrument_storage/data
    networks:
      - spring-boot-postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  instrumentstorage:
    container_name: instrument-storage
    hostname: instrument-storage
    build: .
    ports:
      - "9092:8082"
    expose:
      - 9092
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/instrument_storage
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - spring-boot-postgres
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  db-data:
networks:
  spring-boot-postgres:
    name: music-net