insert into INSTRUMENT (name, category_id)
values
(skrzypce, 1),
(altówka, 1),
(wiolonczela, 1),
(kontrabas, 1),
(harfa, 1),
(gitara, 1),
(lutnia, 1),
(klawesyn, 1),
(fortepian, 1),
(pianino, 1),
(cymbały, 1),
(flet, 2),
(obój, 2),
(rożek angielski, 2),
(klarnet, 2),
(fagot, 2),
(kontrafagot, 2),
(saksofon, 2),
(waltornia, 2),
(trąbka, 2),
(puzon, 2),
(tuba, 2),
(organy, 2),
(akordeon, 2),
(fisharmonia, 2),
(gwizd ludzki, 2),
(kotły, 3),
(bębny, 3),
(gong, 3),
(talerze, 3),
(ksylofon, 3),
(marimba, 3),
(dzwonki, 3),
(czelesta, 3),
(wibrafon, 3),
(dzwony rurowe, 3),
(trójkąt, 3),
(kastaniety, 3),
(pudełka akustyczne, 3),
(klekotka, 3),
(terkotka, 3),
(grzechotka, 3);